    bucket               = "profuturo-infra"
    key                  = "DEV/terraform.tfstate"
    workspace_key_prefix = "terraform"
    dynamodb_table       = "profuturo-lock"
    region               = "eu-west-1"